on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets: 
      API_GITHUB_TOKEN:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 20
      uses: actions/setup-java@v3
      with:
        java-version: '20'
        distribution: 'temurin'
        server-id: github
        settings-path: ${{github.workspace}}

    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{secrets.GITHUB_TOKEN}}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Setup date
      id: date
      run: echo "MY_DATE=$(date '+%Y%m%d%H%M%S')" >> $GITHUB_ENV

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: '.'
        file: ./Dockerfile
        push: true
        platforms: linux/amd64,linux/arm64
        tags: |
          ghcr.io/${{github.repository_owner}}/${{ github.event.repository.name }}:${{env.MY_DATE}}
    outputs:
       my_date: ${{env.MY_DATE}}


  deploy-uat: 
    if: ${{ inputs.logLevel }} == 'uat'
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - run: |
        git clone https://token:${{secrets.API_GITHUB_TOKEN}}@github.com/paulopaniniorg/microservice-configurations.git
        cd microservice-configurations/${{ github.event.repository.name }}
        git remote set-url origin https://token:${{secrets.API_GITHUB_TOKEN}}@github.com/paulopaniniorg/microservice-configurations.git
        git config --global user.email "backstage@benify.com"
        git config --global user.name "backstage"
        sed -i -E "s/(${{ github.event.repository.name }}:)[a-z|0-9]*/${{ github.event.repository.name }}:${{needs.build.outputs.my_date}}/g" deployment.yaml
        git add .
        git commit -m "Deploy ${{needs.build.outputs.my_date}}"
        git push
